# Generated by Django 3.1.11 on 2021-05-21 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ('-bid_price',)},
        ),
    ]
