# Generated by Django 3.1.11 on 2021-05-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_products_minimum_bid_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='minimum_bid_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
