# Generated by Django 3.1.11 on 2021-05-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20210518_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(default=0.0, max_length=200),
            preserve_default=False,
        ),
    ]
