# Generated by Django 3.1.11 on 2021-05-18 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auction_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auction',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
